
server.error.include-message=always
server.error.include-binding-errors=always

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

spring.datasource.username=maha
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgres
mybatis.configuration.map-underscore-to-camel-case=true
spring.servlet.multipart.max-file-size=5000KB
spring.servlet.multipart.max-request-size=5000KB
spring.servlet.multipart.enabled=true
# Show your app logs
logging.level.com.udacity.jwdnd.course1.cloudstorage=DEBUG

# Show MyBatis SQL queries
logging.level.com.udacity.jwdnd.course1.cloudstorage.mapper=DEBUG
logging.level.org.mybatis=DEBUG

mybatis.mapper-locations=classpath:mappers/*.xml
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none